### ISSUE TITLE
Can trusted_certs be a list?

### ISSUE THREAD

**Issue by SocalNick** [cloudfoundry/cflinuxfs3-release#2] opened 2018-05-31 03:08 UTC
Hi,

We just ran into an issue where we inadvertently didn't get an [update to the list of trusted_certs in cflinuxfs2 from a cf-deployment operations file](https://github.com/cloudfoundry/cf-deployment/commit/7eab8f535b206269228621db54b19fb0f00dfc46#diff-7f50200aada6ca3e41a473b3a8c5e0ac) because we had previously overwritten our list of trusted_certs to include a custom one. It would be great if both cf-deployment and operators could provide the trusted_certs as a list that are concatenated together by this release.

Thanks,

Nick

**Comment by SocalNick** [comment] 2018-05-31 03:12
cc @emalm @mhoran @xtreme-jesse-malone @menicosia @syslxg

**Comment by sclevine** [comment] 2018-05-31 03:34
This is a duplicate of https://github.com/cloudfoundry/cflinuxfs2-release/issues/3 which is prioritized here:

https://www.pivotaltracker.com/story/show/155142467

(cflinuxfs3-release is not a working BOSH release for cflinuxfs3 yet.)

**Comment by SocalNick** [comment] 2018-05-31 03:41
Great! I assumed we didn't want to change cflinuxfs2 at this point, but all the better!

**Comment by zmackie** [comment] 2019-09-24 16:09
This was implemented earlier this year.

**Closed as completed by zmackie** 2019-09-24 16:09 UTC
